library(tibble)

# lookup table: pop_sites -> WaterBody
waterbody_sites_lu = tribble(
  ~pop_sites,        ~WaterBody_site,
  "ACB",             "Asotin Creek",
  "ACM",             "Asotin Creek",
  "BRC",             "Bear Valley Creek",
  "TAY",             "Big Creek",
  "BBA",             "Big Bear Creek",
  "KHS",             "Big Bear Creek",
  "BSC",             "Big Sheep Creek",
  "BSC, CMP",        "Big Sheep Creek",
  "CCW",             "Catherine Creek",
  "CLC",             "Clear Creek",
  "ESS",             "East Fork South Fork Salmon River",
  "UGR",             "Grande Ronde River",
  "COC, IR1",        "Imnaha River",
  "IR3",             "Imnaha River",
  "JOC",             "Joseph Creek",
  "LAP",             "Lapwai Creek",
  "LLR",             "Lemhi River",
  "LRL",             "Lochsa River",
  "LC1",             "Lolo Creek",
  "LGW",             "Lookingglass Creek",
  "MAR",             "Marsh Creek",
  "MR1",             "Minam River",
  "MIS",             "Mission Creek",
  "NFS",             "North Fork Salmon River",
  "PCA",             "Panther Creek",
  "HLM",             "Potlatch River",
  "JUL",             "Potlatch River",
  "KHS, PCM",        "Potlatch River",
  "ZEN",             "Secesh River",
  "SW1",             "Selway River",
  "SC1",             "South Fork Clearwater River",
  "KRS",             "South Fork Salmon River",
  "MDC, UGS",        "upper Grande Ronde River",
  "UGS",             "upper Grande Ronde River",
  "VC2",             "Valley Creek",
  "MR1, WR2",        "Wallowa River",
  "WR1",             "Wallowa River",
  "WR2",             "Wallowa River",
  "WEN",             "Wenaha River",
  "WB1",             "Whitebird Creek",
  "YFK",             "Yankee Fork Salmon River",
  "PAHH",            "Pahsimeroi River",
  "RAPH",            "Rapid River",
  "SALEFT",          "East Fork Salmon River",
  "SAWT",            "upper Salmon River",
  # "Multiple" (multi-site time series)
  "ACM, COU",           "Multiple",
  "CRC, LLR",           "Multiple",
  "ESS, KRS",           "Multiple",
  "BED, CLC, LAP",      "Multiple",
  "BED, EPR, LAP, LAW", "Multiple",
  "CLC, HLM, KHS, LAP", "Multiple",
  "CLC, KHS, LAP, PCM", "Multiple",
  "HLM, KHS, LAP",      "Multiple",
  "HLM, MIS",           "Multiple",
  "JA1, LAP",           "Multiple",
  "JA1, SWT",           "Multiple",
  "JUL, LAP",           "Multiple",
  "KHS, LAP",           "Multiple",
  "LAP, LAW, SIX",      "Multiple",
  "LGW, UGR",           "Multiple",
  "VC2, YFK",           "Multiple",
  "RAPH, WB1",          "Multiple"
)

# lookup table: CommonPopName -> WaterBody
waterbody_pop_lu = tribble(
  ~CommonPopName,   ~WaterBody_pop,
  # chinook salmon
  "CRLAP",          "Multiple",
  "CRLOC",          "Lochsa River",
  "CRLOL",          "Multiple",
  "CRPOT",          "Potlatch River",
  "GRCAT",          "Multiple",
  "GRLOO",          "Lookingglass Creek",
  "GRLOS",          "Multiple",
  "GRMIN",          "Minam River",
  "GRUMA",          "Multiple",
  "GRWEN",          "Wenaha River",
  "IRBSH",          "Big Sheep Creek",
  "IRMAI",          "Imnaha River",
  "MFBEA",          "Bear Valley Creek",
  "MFBIG",          "Big Creek",
  "MFMAR",          "Marsh Creek",
  "SCLAW",          "Multiple",
  "SCUMA",          "South Fork Clearwater River",
  "SFEFS",          "East Fork South Fork Salmon River",
  "SFMAI",          "Multiple",
  "SFSEC",          "Secesh River",
  "SNASO",          "Asotin Creek",
  "SREFS",          "East Fork Salmon River",
  "SRLEM",          "Lemhi River",
  "SRLMA",          "Multiple",
  "SRLSR",          "Multiple",
  "SRNFS",          "Multiple",
  "SRPAH",          "Pahsimeroi River",
  "SRPAN",          "Panther Creek",
  "SRUMA",          "upper Salmon River",
  "SRVAL",          "Valley Creek",
  "SRYFS",          "Yankee Fork Salmon River",
  # steelhead
  "CRLMA-s",        "Multiple",
  "CRLOC-s",        "Lochsa River",
  "CRLOL-s",        "Lolo Creek",
  "CRSEL-s",        "Selway River",
  "CRSFC-s",        "South Fork Clearwater River",
  "GRJOS-s",        "Joseph Creek",
  "GRLMT-s",        "Multiple",
  "GRUMA-s",        "Multiple",
  "GRWAL-s",        "Multiple",
  "IRMAI-s",        "Imnaha River",
  "MFBIG-s",        "Multiple",
  "MFUMA-s",        "Multiple",
  "SFMAI-s",        "Multiple",
  "SFSEC-s",        "Secesh River",
  "SNASO-s",        "Multiple",
  "SREFS-s",        "Multiple",
  "SRLEM-s",        "Lemhi River",
  "SRLSR-s",        "Multiple",
  "SRNFS-s",        "Multiple",
  "SRPAH-s",        "Pahsimeroi River",
  "SRPAN-s",        "Multiple",
  "SRUMA-s",        "Multiple"
)