library(tibble)

# lookup table: pop_sites -> WaterBody
waterbody_lu <- tribble(
  ~pop_sites,        ~WaterBody,
  "ACB",             "Asotin Creek",
  "ACM",             "Asotin Creek",
  "BRC",             "Bear Valley Creek",
  "TAY",             "Big Creek",
  "BBA",             "Big Bear Creek",
  "KHS",             "Big Bear Creek",
  "BSC",             "Big Sheep Creek",
  "BSC, CMP",        "Big Sheep Creek",
  "CCW",             "Catherine Creek",
  "CLC",             "Clear Creek",
  "ESS",             "East Fork South Fork Salmon River",
  "UGR",             "Grande Ronde River",
  "COC, IR1",        "Imnaha River",
  "IR3",             "Imnaha River",
  "JOC",             "Joseph Creek",
  "LAP",             "Lapwai Creek",
  "LLR",             "Lemhi River",
  "LRL",             "Lochsa River",
  "LC1",             "Lolo Creek",
  "LGW",             "Lookingglass Creek",
  "MAR",             "Marsh Creek",
  "MR1",             "Minam River",
  "MIS",             "Mission Creek",
  "NFS",             "North Fork Salmon River",
  "PCA",             "Panther Creek",
  "HLM",             "Potlatch River",
  "JUL",             "Potlatch River",
  "KHS, PCM",        "Potlatch River",
  "ZEN",             "Secesh River",
  "SW1",             "Selway River",
  "SC1",             "South Fork Clearwater River",
  "KRS",             "South Fork Salmon River",
  "MDC, UGS",        "upper Grande Ronde River",
  "UGS",             "upper Grande Ronde River",
  "VC2",             "Valley Creek",
  "MR1, WR2",        "Wallowa River",
  "WR1",             "Wallowa River",
  "WR2",             "Wallowa River",
  "WEN",             "Wenaha River",
  "WB1",             "Whitebird Creek",
  "YFK",             "Yankee Fork Salmon River",
  # "Multiple" (multi-site time series)
  "ACM, COU",           "Multiple",
  "CRC, LLR",           "Multiple",
  "ESS, KRS",           "Multiple",
  "BED, CLC, LAP",      "Multiple",
  "BED, EPR, LAP, LAW", "Multiple",
  "CLC, HLM, KHS, LAP", "Multiple",
  "CLC, KHS, LAP, PCM", "Multiple",
  "HLM, KHS, LAP",      "Multiple",
  "HLM, MIS",           "Multiple",
  "JA1, LAP",           "Multiple",
  "JA1, SWT",           "Multiple",
  "JUL, LAP",           "Multiple",
  "KHS, LAP",           "Multiple",
  "LAP, LAW, SIX",      "Multiple",
  "LGW, UGR",           "Multiple",
  "VC2, YFK",           "Multiple"
)